name: Build Armbian Kernel (Forky)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Armbian Kernel
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "orangepi5-plus"
          armbian_release: "forky"
          armbian_target: "kernel"      # Собираем только ядро
          armbian_ui: "minimal"
          armbian_kernel_branch: "edge"
          armbian_runner_clean: "no"    # Важно для подхвата userpatches

      - name: Upload Kernel Packages
        uses: actions/upload-artifact@v4
        with:
          name: armbian-kernel-packages
          path: build/output/debs/*.deb
          if-no-files-found: error
