name: Build Armbian Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Armbian Kernel
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "orangepi5-plus"
          armbian_release: "trixie"
          armbian_target: "kernel"
          armbian_ui: "minimal"
          armbian_kernel_branch: "edge"
          armbian_runner_clean: "no"

      - name: Verify Kernel Config
        run: |
          # Переходим в папку с дебами
          cd build/output/debs/
          IMAGE_PKG=$(ls linux-image-edge-rockchip64_*.deb | head -n 1)
          echo "Checking package: $IMAGE_PKG"
          
          # Распаковываем конфиг
          ar x "$IMAGE_PKG" data.tar.xz
          tar -xJf data.tar.xz --wildcards './boot/config-*'
          
          echo "--- FINAL KERNEL CONFIG CHECK ---"
          grep "CONFIG_CPU_FREQ_GOV_ONDEMAND" boot/config-*
          echo "---------------------------------"

      - name: Upload Kernel Packages
        uses: actions/upload-artifact@v4
        with:
          name: armbian-kernel-packages
          # Указываем правильный путь для DEB пакетов
          path: build/output/debs/*.deb
          if-no-files-found: error
